# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_newspaper_links": "00_core.ipynb",
         "get_download_urls": "00_core.ipynb",
         "create_session": "00_core.ipynb",
         "download_from_urls": "00_core.ipynb",
         "cli": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://Living-with-machines.github.io/hmd_newspaper_dl/"

git_url = "https://github.com/Living-with-machines/hmd_newspaper_dl/tree/main/"

def custom_doc_links(name): return None
